// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/brewmmer/recepie.proto

package brewmmer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IngredientType int32

const (
	IngredientType_NULL_INGREDIENT_TYPE IngredientType = 0
	IngredientType_WATER                IngredientType = 1
	IngredientType_MALT                 IngredientType = 2
	IngredientType_HOPS                 IngredientType = 3
	IngredientType_YIEST                IngredientType = 4
)

var IngredientType_name = map[int32]string{
	0: "NULL_INGREDIENT_TYPE",
	1: "WATER",
	2: "MALT",
	3: "HOPS",
	4: "YIEST",
}
var IngredientType_value = map[string]int32{
	"NULL_INGREDIENT_TYPE": 0,
	"WATER":                1,
	"MALT":                 2,
	"HOPS":                 3,
	"YIEST":                4,
}

func (x IngredientType) String() string {
	return proto.EnumName(IngredientType_name, int32(x))
}
func (IngredientType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_recepie_829b8444e2505d5e, []int{0}
}

type Unit int32

const (
	Unit_NULL_UNIT Unit = 0
	Unit_L         Unit = 1
	Unit_G         Unit = 2
	Unit_KG        Unit = 3
	Unit_MIN       Unit = 4
	Unit_DAY       Unit = 5
)

var Unit_name = map[int32]string{
	0: "NULL_UNIT",
	1: "L",
	2: "G",
	3: "KG",
	4: "MIN",
	5: "DAY",
}
var Unit_value = map[string]int32{
	"NULL_UNIT": 0,
	"L":         1,
	"G":         2,
	"KG":        3,
	"MIN":       4,
	"DAY":       5,
}

func (x Unit) String() string {
	return proto.EnumName(Unit_name, int32(x))
}
func (Unit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_recepie_829b8444e2505d5e, []int{1}
}

type Phase int32

const (
	Phase_INIT         Phase = 0
	Phase_MASHING      Phase = 1
	Phase_BOILING      Phase = 2
	Phase_SPARGING     Phase = 3
	Phase_CHILLING     Phase = 4
	Phase_FERMENTATION Phase = 5
	Phase_BOTTLING     Phase = 6
)

var Phase_name = map[int32]string{
	0: "INIT",
	1: "MASHING",
	2: "BOILING",
	3: "SPARGING",
	4: "CHILLING",
	5: "FERMENTATION",
	6: "BOTTLING",
}
var Phase_value = map[string]int32{
	"INIT":         0,
	"MASHING":      1,
	"BOILING":      2,
	"SPARGING":     3,
	"CHILLING":     4,
	"FERMENTATION": 5,
	"BOTTLING":     6,
}

func (x Phase) String() string {
	return proto.EnumName(Phase_name, int32(x))
}
func (Phase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_recepie_829b8444e2505d5e, []int{2}
}

type GetRecipeRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecipeRequest) Reset()         { *m = GetRecipeRequest{} }
func (m *GetRecipeRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecipeRequest) ProtoMessage()    {}
func (*GetRecipeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_829b8444e2505d5e, []int{0}
}
func (m *GetRecipeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecipeRequest.Unmarshal(m, b)
}
func (m *GetRecipeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecipeRequest.Marshal(b, m, deterministic)
}
func (dst *GetRecipeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecipeRequest.Merge(dst, src)
}
func (m *GetRecipeRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecipeRequest.Size(m)
}
func (m *GetRecipeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecipeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecipeRequest proto.InternalMessageInfo

func (m *GetRecipeRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetRecipeResponse struct {
	Recipe               *Recipe  `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecipeResponse) Reset()         { *m = GetRecipeResponse{} }
func (m *GetRecipeResponse) String() string { return proto.CompactTextString(m) }
func (*GetRecipeResponse) ProtoMessage()    {}
func (*GetRecipeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_829b8444e2505d5e, []int{1}
}
func (m *GetRecipeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecipeResponse.Unmarshal(m, b)
}
func (m *GetRecipeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecipeResponse.Marshal(b, m, deterministic)
}
func (dst *GetRecipeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecipeResponse.Merge(dst, src)
}
func (m *GetRecipeResponse) XXX_Size() int {
	return xxx_messageInfo_GetRecipeResponse.Size(m)
}
func (m *GetRecipeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecipeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecipeResponse proto.InternalMessageInfo

func (m *GetRecipeResponse) GetRecipe() *Recipe {
	if m != nil {
		return m.Recipe
	}
	return nil
}

type CreateRecipeRequest struct {
	Recipe               *Recipe  `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRecipeRequest) Reset()         { *m = CreateRecipeRequest{} }
func (m *CreateRecipeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRecipeRequest) ProtoMessage()    {}
func (*CreateRecipeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_829b8444e2505d5e, []int{2}
}
func (m *CreateRecipeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRecipeRequest.Unmarshal(m, b)
}
func (m *CreateRecipeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRecipeRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRecipeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRecipeRequest.Merge(dst, src)
}
func (m *CreateRecipeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRecipeRequest.Size(m)
}
func (m *CreateRecipeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRecipeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRecipeRequest proto.InternalMessageInfo

func (m *CreateRecipeRequest) GetRecipe() *Recipe {
	if m != nil {
		return m.Recipe
	}
	return nil
}

type CreateRecipeResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRecipeResponse) Reset()         { *m = CreateRecipeResponse{} }
func (m *CreateRecipeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRecipeResponse) ProtoMessage()    {}
func (*CreateRecipeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_829b8444e2505d5e, []int{3}
}
func (m *CreateRecipeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRecipeResponse.Unmarshal(m, b)
}
func (m *CreateRecipeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRecipeResponse.Marshal(b, m, deterministic)
}
func (dst *CreateRecipeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRecipeResponse.Merge(dst, src)
}
func (m *CreateRecipeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRecipeResponse.Size(m)
}
func (m *CreateRecipeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRecipeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRecipeResponse proto.InternalMessageInfo

func (m *CreateRecipeResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateRecipeRequest struct {
	Recipe               *Recipe  `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRecipeRequest) Reset()         { *m = UpdateRecipeRequest{} }
func (m *UpdateRecipeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRecipeRequest) ProtoMessage()    {}
func (*UpdateRecipeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_829b8444e2505d5e, []int{4}
}
func (m *UpdateRecipeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRecipeRequest.Unmarshal(m, b)
}
func (m *UpdateRecipeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRecipeRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRecipeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRecipeRequest.Merge(dst, src)
}
func (m *UpdateRecipeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRecipeRequest.Size(m)
}
func (m *UpdateRecipeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRecipeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRecipeRequest proto.InternalMessageInfo

func (m *UpdateRecipeRequest) GetRecipe() *Recipe {
	if m != nil {
		return m.Recipe
	}
	return nil
}

type UpdateRecipeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRecipeResponse) Reset()         { *m = UpdateRecipeResponse{} }
func (m *UpdateRecipeResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRecipeResponse) ProtoMessage()    {}
func (*UpdateRecipeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_829b8444e2505d5e, []int{5}
}
func (m *UpdateRecipeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRecipeResponse.Unmarshal(m, b)
}
func (m *UpdateRecipeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRecipeResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateRecipeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRecipeResponse.Merge(dst, src)
}
func (m *UpdateRecipeResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRecipeResponse.Size(m)
}
func (m *UpdateRecipeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRecipeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRecipeResponse proto.InternalMessageInfo

type DeleteRecipeRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRecipeRequest) Reset()         { *m = DeleteRecipeRequest{} }
func (m *DeleteRecipeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRecipeRequest) ProtoMessage()    {}
func (*DeleteRecipeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_829b8444e2505d5e, []int{6}
}
func (m *DeleteRecipeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRecipeRequest.Unmarshal(m, b)
}
func (m *DeleteRecipeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRecipeRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRecipeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRecipeRequest.Merge(dst, src)
}
func (m *DeleteRecipeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRecipeRequest.Size(m)
}
func (m *DeleteRecipeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRecipeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRecipeRequest proto.InternalMessageInfo

func (m *DeleteRecipeRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteRecipeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRecipeResponse) Reset()         { *m = DeleteRecipeResponse{} }
func (m *DeleteRecipeResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRecipeResponse) ProtoMessage()    {}
func (*DeleteRecipeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_829b8444e2505d5e, []int{7}
}
func (m *DeleteRecipeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRecipeResponse.Unmarshal(m, b)
}
func (m *DeleteRecipeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRecipeResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteRecipeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRecipeResponse.Merge(dst, src)
}
func (m *DeleteRecipeResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRecipeResponse.Size(m)
}
func (m *DeleteRecipeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRecipeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRecipeResponse proto.InternalMessageInfo

type ListRecipeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRecipeRequest) Reset()         { *m = ListRecipeRequest{} }
func (m *ListRecipeRequest) String() string { return proto.CompactTextString(m) }
func (*ListRecipeRequest) ProtoMessage()    {}
func (*ListRecipeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_829b8444e2505d5e, []int{8}
}
func (m *ListRecipeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecipeRequest.Unmarshal(m, b)
}
func (m *ListRecipeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecipeRequest.Marshal(b, m, deterministic)
}
func (dst *ListRecipeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecipeRequest.Merge(dst, src)
}
func (m *ListRecipeRequest) XXX_Size() int {
	return xxx_messageInfo_ListRecipeRequest.Size(m)
}
func (m *ListRecipeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecipeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecipeRequest proto.InternalMessageInfo

type ListRecipeResponse struct {
	Recipes              []*Recipe `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListRecipeResponse) Reset()         { *m = ListRecipeResponse{} }
func (m *ListRecipeResponse) String() string { return proto.CompactTextString(m) }
func (*ListRecipeResponse) ProtoMessage()    {}
func (*ListRecipeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_829b8444e2505d5e, []int{9}
}
func (m *ListRecipeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecipeResponse.Unmarshal(m, b)
}
func (m *ListRecipeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecipeResponse.Marshal(b, m, deterministic)
}
func (dst *ListRecipeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecipeResponse.Merge(dst, src)
}
func (m *ListRecipeResponse) XXX_Size() int {
	return xxx_messageInfo_ListRecipeResponse.Size(m)
}
func (m *ListRecipeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecipeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecipeResponse proto.InternalMessageInfo

func (m *ListRecipeResponse) GetRecipes() []*Recipe {
	if m != nil {
		return m.Recipes
	}
	return nil
}

type Quantity struct {
	Volume               float32  `protobuf:"fixed32,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Unit                 Unit     `protobuf:"varint,2,opt,name=unit,proto3,enum=brewmmer.Unit" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quantity) Reset()         { *m = Quantity{} }
func (m *Quantity) String() string { return proto.CompactTextString(m) }
func (*Quantity) ProtoMessage()    {}
func (*Quantity) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_829b8444e2505d5e, []int{10}
}
func (m *Quantity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quantity.Unmarshal(m, b)
}
func (m *Quantity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quantity.Marshal(b, m, deterministic)
}
func (dst *Quantity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quantity.Merge(dst, src)
}
func (m *Quantity) XXX_Size() int {
	return xxx_messageInfo_Quantity.Size(m)
}
func (m *Quantity) XXX_DiscardUnknown() {
	xxx_messageInfo_Quantity.DiscardUnknown(m)
}

var xxx_messageInfo_Quantity proto.InternalMessageInfo

func (m *Quantity) GetVolume() float32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Quantity) GetUnit() Unit {
	if m != nil {
		return m.Unit
	}
	return Unit_NULL_UNIT
}

type Ingredient struct {
	Type                 IngredientType `protobuf:"varint,1,opt,name=type,proto3,enum=brewmmer.IngredientType" json:"type,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity             *Quantity      `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Ingredient) Reset()         { *m = Ingredient{} }
func (m *Ingredient) String() string { return proto.CompactTextString(m) }
func (*Ingredient) ProtoMessage()    {}
func (*Ingredient) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_829b8444e2505d5e, []int{11}
}
func (m *Ingredient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ingredient.Unmarshal(m, b)
}
func (m *Ingredient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ingredient.Marshal(b, m, deterministic)
}
func (dst *Ingredient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ingredient.Merge(dst, src)
}
func (m *Ingredient) XXX_Size() int {
	return xxx_messageInfo_Ingredient.Size(m)
}
func (m *Ingredient) XXX_DiscardUnknown() {
	xxx_messageInfo_Ingredient.DiscardUnknown(m)
}

var xxx_messageInfo_Ingredient proto.InternalMessageInfo

func (m *Ingredient) GetType() IngredientType {
	if m != nil {
		return m.Type
	}
	return IngredientType_NULL_INGREDIENT_TYPE
}

func (m *Ingredient) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ingredient) GetQuantity() *Quantity {
	if m != nil {
		return m.Quantity
	}
	return nil
}

type Step struct {
	Phase                Phase         `protobuf:"varint,1,opt,name=phase,proto3,enum=brewmmer.Phase" json:"phase,omitempty"`
	Temperature          int32         `protobuf:"varint,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Duration             *Quantity     `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Ingredients          []*Ingredient `protobuf:"bytes,4,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_829b8444e2505d5e, []int{12}
}
func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (dst *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(dst, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetPhase() Phase {
	if m != nil {
		return m.Phase
	}
	return Phase_INIT
}

func (m *Step) GetTemperature() int32 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

func (m *Step) GetDuration() *Quantity {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *Step) GetIngredients() []*Ingredient {
	if m != nil {
		return m.Ingredients
	}
	return nil
}

type Recipe struct {
	Id                   int32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Ingredients          []*Ingredient `protobuf:"bytes,4,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	Steps                []*Step       `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Recipe) Reset()         { *m = Recipe{} }
func (m *Recipe) String() string { return proto.CompactTextString(m) }
func (*Recipe) ProtoMessage()    {}
func (*Recipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_829b8444e2505d5e, []int{13}
}
func (m *Recipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recipe.Unmarshal(m, b)
}
func (m *Recipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recipe.Marshal(b, m, deterministic)
}
func (dst *Recipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recipe.Merge(dst, src)
}
func (m *Recipe) XXX_Size() int {
	return xxx_messageInfo_Recipe.Size(m)
}
func (m *Recipe) XXX_DiscardUnknown() {
	xxx_messageInfo_Recipe.DiscardUnknown(m)
}

var xxx_messageInfo_Recipe proto.InternalMessageInfo

func (m *Recipe) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Recipe) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Recipe) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Recipe) GetIngredients() []*Ingredient {
	if m != nil {
		return m.Ingredients
	}
	return nil
}

func (m *Recipe) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRecipeRequest)(nil), "brewmmer.GetRecipeRequest")
	proto.RegisterType((*GetRecipeResponse)(nil), "brewmmer.GetRecipeResponse")
	proto.RegisterType((*CreateRecipeRequest)(nil), "brewmmer.CreateRecipeRequest")
	proto.RegisterType((*CreateRecipeResponse)(nil), "brewmmer.CreateRecipeResponse")
	proto.RegisterType((*UpdateRecipeRequest)(nil), "brewmmer.UpdateRecipeRequest")
	proto.RegisterType((*UpdateRecipeResponse)(nil), "brewmmer.UpdateRecipeResponse")
	proto.RegisterType((*DeleteRecipeRequest)(nil), "brewmmer.DeleteRecipeRequest")
	proto.RegisterType((*DeleteRecipeResponse)(nil), "brewmmer.DeleteRecipeResponse")
	proto.RegisterType((*ListRecipeRequest)(nil), "brewmmer.ListRecipeRequest")
	proto.RegisterType((*ListRecipeResponse)(nil), "brewmmer.ListRecipeResponse")
	proto.RegisterType((*Quantity)(nil), "brewmmer.Quantity")
	proto.RegisterType((*Ingredient)(nil), "brewmmer.Ingredient")
	proto.RegisterType((*Step)(nil), "brewmmer.Step")
	proto.RegisterType((*Recipe)(nil), "brewmmer.Recipe")
	proto.RegisterEnum("brewmmer.IngredientType", IngredientType_name, IngredientType_value)
	proto.RegisterEnum("brewmmer.Unit", Unit_name, Unit_value)
	proto.RegisterEnum("brewmmer.Phase", Phase_name, Phase_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecipeServiceClient is the client API for RecipeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecipeServiceClient interface {
	Get(ctx context.Context, in *GetRecipeRequest, opts ...grpc.CallOption) (*GetRecipeResponse, error)
	Create(ctx context.Context, in *CreateRecipeRequest, opts ...grpc.CallOption) (*CreateRecipeResponse, error)
	Update(ctx context.Context, in *UpdateRecipeRequest, opts ...grpc.CallOption) (*UpdateRecipeResponse, error)
	Delete(ctx context.Context, in *DeleteRecipeRequest, opts ...grpc.CallOption) (*DeleteRecipeResponse, error)
	List(ctx context.Context, in *ListRecipeRequest, opts ...grpc.CallOption) (*ListRecipeResponse, error)
}

type recipeServiceClient struct {
	cc *grpc.ClientConn
}

func NewRecipeServiceClient(cc *grpc.ClientConn) RecipeServiceClient {
	return &recipeServiceClient{cc}
}

func (c *recipeServiceClient) Get(ctx context.Context, in *GetRecipeRequest, opts ...grpc.CallOption) (*GetRecipeResponse, error) {
	out := new(GetRecipeResponse)
	err := c.cc.Invoke(ctx, "/brewmmer.RecipeService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) Create(ctx context.Context, in *CreateRecipeRequest, opts ...grpc.CallOption) (*CreateRecipeResponse, error) {
	out := new(CreateRecipeResponse)
	err := c.cc.Invoke(ctx, "/brewmmer.RecipeService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) Update(ctx context.Context, in *UpdateRecipeRequest, opts ...grpc.CallOption) (*UpdateRecipeResponse, error) {
	out := new(UpdateRecipeResponse)
	err := c.cc.Invoke(ctx, "/brewmmer.RecipeService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) Delete(ctx context.Context, in *DeleteRecipeRequest, opts ...grpc.CallOption) (*DeleteRecipeResponse, error) {
	out := new(DeleteRecipeResponse)
	err := c.cc.Invoke(ctx, "/brewmmer.RecipeService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recipeServiceClient) List(ctx context.Context, in *ListRecipeRequest, opts ...grpc.CallOption) (*ListRecipeResponse, error) {
	out := new(ListRecipeResponse)
	err := c.cc.Invoke(ctx, "/brewmmer.RecipeService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecipeServiceServer is the server API for RecipeService service.
type RecipeServiceServer interface {
	Get(context.Context, *GetRecipeRequest) (*GetRecipeResponse, error)
	Create(context.Context, *CreateRecipeRequest) (*CreateRecipeResponse, error)
	Update(context.Context, *UpdateRecipeRequest) (*UpdateRecipeResponse, error)
	Delete(context.Context, *DeleteRecipeRequest) (*DeleteRecipeResponse, error)
	List(context.Context, *ListRecipeRequest) (*ListRecipeResponse, error)
}

func RegisterRecipeServiceServer(s *grpc.Server, srv RecipeServiceServer) {
	s.RegisterService(&_RecipeService_serviceDesc, srv)
}

func _RecipeService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/brewmmer.RecipeService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).Get(ctx, req.(*GetRecipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/brewmmer.RecipeService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).Create(ctx, req.(*CreateRecipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRecipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/brewmmer.RecipeService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).Update(ctx, req.(*UpdateRecipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRecipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/brewmmer.RecipeService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).Delete(ctx, req.(*DeleteRecipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecipeService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/brewmmer.RecipeService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).List(ctx, req.(*ListRecipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RecipeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "brewmmer.RecipeService",
	HandlerType: (*RecipeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _RecipeService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _RecipeService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _RecipeService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RecipeService_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _RecipeService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/brewmmer/recepie.proto",
}

func init() { proto.RegisterFile("api/brewmmer/recepie.proto", fileDescriptor_recepie_829b8444e2505d5e) }

var fileDescriptor_recepie_829b8444e2505d5e = []byte{
	// 713 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x5d, 0x6f, 0xda, 0x4a,
	0x10, 0x8d, 0xbf, 0x08, 0x0c, 0x09, 0x77, 0x33, 0xa0, 0xc8, 0xe2, 0xde, 0x5b, 0x21, 0xab, 0xa9,
	0x22, 0x54, 0x11, 0x89, 0x4a, 0x7d, 0x4b, 0x53, 0x92, 0x10, 0xc7, 0x2a, 0x18, 0xba, 0x18, 0x55,
	0x79, 0x8a, 0x08, 0xac, 0x52, 0x4b, 0xc1, 0x38, 0xf6, 0x92, 0x2a, 0x2f, 0xfd, 0x45, 0x7d, 0xef,
	0xaf, 0xea, 0x7f, 0xa8, 0xd6, 0x36, 0xb1, 0xa1, 0x6e, 0x55, 0xb5, 0x4f, 0xec, 0xce, 0x39, 0x7b,
	0x66, 0x76, 0x66, 0x39, 0x86, 0xfa, 0xc4, 0x77, 0x8f, 0x6e, 0x02, 0xf6, 0x69, 0x3e, 0x67, 0xc1,
	0x51, 0xc0, 0xa6, 0xcc, 0x77, 0x59, 0xcb, 0x0f, 0x16, 0x7c, 0x81, 0xc5, 0x55, 0xdc, 0x30, 0x80,
	0x98, 0x8c, 0x53, 0x36, 0x75, 0x7d, 0x46, 0xd9, 0xfd, 0x92, 0x85, 0x1c, 0x2b, 0x20, 0xbb, 0x33,
	0x5d, 0x6a, 0x48, 0x87, 0x0a, 0x95, 0xdd, 0x99, 0x71, 0x0c, 0x7b, 0x19, 0x4e, 0xe8, 0x2f, 0xbc,
	0x90, 0xe1, 0x21, 0x14, 0x82, 0x28, 0x12, 0x11, 0xcb, 0x6d, 0xd2, 0x5a, 0x69, 0xb6, 0x12, 0x66,
	0x82, 0x1b, 0x27, 0x50, 0x3d, 0x0b, 0xd8, 0x84, 0xb3, 0xf5, 0x2c, 0xbf, 0x2f, 0xf0, 0x02, 0x6a,
	0xeb, 0x02, 0x49, 0x09, 0x9b, 0x75, 0x9e, 0x40, 0x75, 0xec, 0xcf, 0xfe, 0x22, 0xd1, 0x3e, 0xd4,
	0xd6, 0x05, 0xe2, 0x44, 0xc6, 0x01, 0x54, 0xcf, 0xd9, 0x1d, 0xdb, 0x14, 0xde, 0xcc, 0xbf, 0x0f,
	0xb5, 0x75, 0x5a, 0x72, 0xbc, 0x0a, 0x7b, 0x3d, 0x37, 0x5c, 0x6f, 0xb2, 0xf1, 0x16, 0x30, 0x1b,
	0x4c, 0xae, 0xd4, 0x84, 0xed, 0xb8, 0x96, 0x50, 0x97, 0x1a, 0x4a, 0x6e, 0xb1, 0x2b, 0x82, 0x71,
	0x01, 0xc5, 0xf7, 0xcb, 0x89, 0xc7, 0x5d, 0xfe, 0x88, 0xfb, 0x50, 0x78, 0x58, 0xdc, 0x2d, 0xe7,
	0xf1, 0x1d, 0x65, 0x9a, 0xec, 0xd0, 0x00, 0x75, 0xe9, 0xb9, 0x5c, 0x97, 0x1b, 0xd2, 0x61, 0xa5,
	0x5d, 0x49, 0xc5, 0xc6, 0x9e, 0xcb, 0x69, 0x84, 0x19, 0x9f, 0x01, 0x2c, 0xef, 0x36, 0x60, 0x33,
	0x97, 0x79, 0x1c, 0x5f, 0x82, 0xca, 0x1f, 0x93, 0x5e, 0x55, 0xda, 0x7a, 0x7a, 0x22, 0xe5, 0x38,
	0x8f, 0x3e, 0xa3, 0x11, 0x0b, 0x11, 0x54, 0x6f, 0x32, 0x67, 0x91, 0x7e, 0x89, 0x46, 0x6b, 0x6c,
	0x41, 0xf1, 0x3e, 0xa9, 0x4b, 0x57, 0xa2, 0x8e, 0x63, 0xaa, 0xb2, 0xaa, 0x98, 0x3e, 0x71, 0x8c,
	0xaf, 0x12, 0xa8, 0x23, 0xce, 0x7c, 0x3c, 0x00, 0xcd, 0xff, 0x38, 0x09, 0x57, 0xb9, 0xff, 0x49,
	0x4f, 0x0d, 0x45, 0x98, 0xc6, 0x28, 0x36, 0xa0, 0xcc, 0xd9, 0xdc, 0x67, 0xc1, 0x84, 0x2f, 0x83,
	0x38, 0xb5, 0x46, 0xb3, 0x21, 0x51, 0xc1, 0x6c, 0x19, 0x4c, 0xb8, 0xbb, 0xf0, 0x7e, 0x55, 0xc1,
	0x8a, 0x83, 0xaf, 0xa1, 0xec, 0x3e, 0xdd, 0x2e, 0xd4, 0xd5, 0xa8, 0xf3, 0xb5, 0xbc, 0xab, 0xd3,
	0x2c, 0xd1, 0xf8, 0x22, 0x41, 0x21, 0x9e, 0x4a, 0xe6, 0x2d, 0x68, 0xe2, 0x2d, 0xe4, 0x36, 0xa6,
	0x01, 0xe5, 0x19, 0x0b, 0xa7, 0x81, 0xeb, 0x3f, 0x55, 0x56, 0xa2, 0xd9, 0xd0, 0x9f, 0x16, 0x82,
	0xcf, 0x41, 0x0b, 0x39, 0xf3, 0x43, 0x5d, 0x8b, 0x4e, 0x64, 0xe6, 0x2c, 0x1a, 0x4b, 0x63, 0xb0,
	0xe9, 0x40, 0x65, 0x7d, 0x88, 0xa8, 0x43, 0xcd, 0x1e, 0xf7, 0x7a, 0xd7, 0x96, 0x6d, 0xd2, 0xee,
	0xb9, 0xd5, 0xb5, 0x9d, 0x6b, 0xe7, 0x6a, 0xd8, 0x25, 0x5b, 0x58, 0x02, 0xed, 0x43, 0xc7, 0xe9,
	0x52, 0x22, 0x61, 0x11, 0xd4, 0x7e, 0xa7, 0xe7, 0x10, 0x59, 0xac, 0x2e, 0x07, 0xc3, 0x11, 0x51,
	0x04, 0x7c, 0x65, 0x75, 0x47, 0x0e, 0x51, 0x9b, 0xc7, 0xa0, 0x8a, 0xc7, 0x84, 0xbb, 0x50, 0x8a,
	0xb4, 0xc6, 0xb6, 0xe5, 0x90, 0x2d, 0xd4, 0x40, 0xea, 0x11, 0x49, 0xfc, 0x98, 0x44, 0xc6, 0x02,
	0xc8, 0xef, 0x4c, 0xa2, 0xe0, 0x36, 0x28, 0x7d, 0xcb, 0x26, 0xaa, 0x58, 0x9c, 0x77, 0xae, 0x88,
	0xd6, 0xbc, 0x05, 0x2d, 0x9a, 0xae, 0x10, 0xb7, 0xe2, 0xa3, 0x65, 0xd8, 0xee, 0x77, 0x46, 0x97,
	0x96, 0x6d, 0x12, 0x49, 0x6c, 0x4e, 0x07, 0x56, 0x4f, 0x6c, 0x64, 0xdc, 0x81, 0xe2, 0x68, 0xd8,
	0xa1, 0xa6, 0xd8, 0x29, 0x62, 0x77, 0x76, 0x69, 0xf5, 0x22, 0x4c, 0x45, 0x02, 0x3b, 0x17, 0x5d,
	0xda, 0xef, 0xda, 0x4e, 0xc7, 0xb1, 0x06, 0x36, 0xd1, 0x04, 0x7e, 0x3a, 0x70, 0x9c, 0x08, 0x2f,
	0xb4, 0xbf, 0xc9, 0xb0, 0x1b, 0x0f, 0x6b, 0xc4, 0x82, 0x07, 0x77, 0xca, 0xf0, 0x0d, 0x28, 0x26,
	0xe3, 0x58, 0x4f, 0xbb, 0xb5, 0x69, 0x85, 0xf5, 0x7f, 0x73, 0xb1, 0xe4, 0xcf, 0x6a, 0x42, 0x21,
	0xf6, 0x25, 0xfc, 0x3f, 0xa5, 0xe5, 0x58, 0x5d, 0xfd, 0xd9, 0xcf, 0xe0, 0x54, 0x28, 0xf6, 0x9d,
	0xac, 0x50, 0x8e, 0x95, 0x65, 0x85, 0xf2, 0x8c, 0x4a, 0x08, 0xc5, 0x0e, 0x94, 0x15, 0xca, 0xb1,
	0xae, 0xac, 0x50, 0x9e, 0x65, 0x61, 0x07, 0x54, 0xe1, 0x4e, 0x98, 0xb9, 0xff, 0x0f, 0x16, 0x56,
	0xff, 0x2f, 0x1f, 0x8c, 0x25, 0x6e, 0x0a, 0xd1, 0xa7, 0xe6, 0xd5, 0xf7, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x06, 0x1a, 0x3a, 0x9c, 0x88, 0x06, 0x00, 0x00,
}
