// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/brewmmer/recepie.proto

package brewmmer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IngredientType int32

const (
	IngredientType_NULL_INGREDIENT_TYPE IngredientType = 0
	IngredientType_WATER                IngredientType = 1
	IngredientType_MALT                 IngredientType = 2
	IngredientType_HOPS                 IngredientType = 3
	IngredientType_YIEST                IngredientType = 4
)

var IngredientType_name = map[int32]string{
	0: "NULL_INGREDIENT_TYPE",
	1: "WATER",
	2: "MALT",
	3: "HOPS",
	4: "YIEST",
}
var IngredientType_value = map[string]int32{
	"NULL_INGREDIENT_TYPE": 0,
	"WATER":                1,
	"MALT":                 2,
	"HOPS":                 3,
	"YIEST":                4,
}

func (x IngredientType) String() string {
	return proto.EnumName(IngredientType_name, int32(x))
}
func (IngredientType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_recepie_9d90ce52d6af1e66, []int{0}
}

type Unit int32

const (
	Unit_NULL_UNIT Unit = 0
	Unit_L         Unit = 1
	Unit_G         Unit = 2
	Unit_KG        Unit = 3
	Unit_MIN       Unit = 4
	Unit_DAY       Unit = 5
)

var Unit_name = map[int32]string{
	0: "NULL_UNIT",
	1: "L",
	2: "G",
	3: "KG",
	4: "MIN",
	5: "DAY",
}
var Unit_value = map[string]int32{
	"NULL_UNIT": 0,
	"L":         1,
	"G":         2,
	"KG":        3,
	"MIN":       4,
	"DAY":       5,
}

func (x Unit) String() string {
	return proto.EnumName(Unit_name, int32(x))
}
func (Unit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_recepie_9d90ce52d6af1e66, []int{1}
}

type Phase int32

const (
	Phase_INIT         Phase = 0
	Phase_MASHING      Phase = 1
	Phase_BOILING      Phase = 2
	Phase_SPARGING     Phase = 3
	Phase_CHILLING     Phase = 4
	Phase_FERMENTATION Phase = 5
	Phase_BOTTLING     Phase = 6
)

var Phase_name = map[int32]string{
	0: "INIT",
	1: "MASHING",
	2: "BOILING",
	3: "SPARGING",
	4: "CHILLING",
	5: "FERMENTATION",
	6: "BOTTLING",
}
var Phase_value = map[string]int32{
	"INIT":         0,
	"MASHING":      1,
	"BOILING":      2,
	"SPARGING":     3,
	"CHILLING":     4,
	"FERMENTATION": 5,
	"BOTTLING":     6,
}

func (x Phase) String() string {
	return proto.EnumName(Phase_name, int32(x))
}
func (Phase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_recepie_9d90ce52d6af1e66, []int{2}
}

type GetRecepieRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecepieRequest) Reset()         { *m = GetRecepieRequest{} }
func (m *GetRecepieRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecepieRequest) ProtoMessage()    {}
func (*GetRecepieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_9d90ce52d6af1e66, []int{0}
}
func (m *GetRecepieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecepieRequest.Unmarshal(m, b)
}
func (m *GetRecepieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecepieRequest.Marshal(b, m, deterministic)
}
func (dst *GetRecepieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecepieRequest.Merge(dst, src)
}
func (m *GetRecepieRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecepieRequest.Size(m)
}
func (m *GetRecepieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecepieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecepieRequest proto.InternalMessageInfo

func (m *GetRecepieRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetRecepieResponse struct {
	Recepie              *Recepie `protobuf:"bytes,1,opt,name=recepie,proto3" json:"recepie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecepieResponse) Reset()         { *m = GetRecepieResponse{} }
func (m *GetRecepieResponse) String() string { return proto.CompactTextString(m) }
func (*GetRecepieResponse) ProtoMessage()    {}
func (*GetRecepieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_9d90ce52d6af1e66, []int{1}
}
func (m *GetRecepieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecepieResponse.Unmarshal(m, b)
}
func (m *GetRecepieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecepieResponse.Marshal(b, m, deterministic)
}
func (dst *GetRecepieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecepieResponse.Merge(dst, src)
}
func (m *GetRecepieResponse) XXX_Size() int {
	return xxx_messageInfo_GetRecepieResponse.Size(m)
}
func (m *GetRecepieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecepieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecepieResponse proto.InternalMessageInfo

func (m *GetRecepieResponse) GetRecepie() *Recepie {
	if m != nil {
		return m.Recepie
	}
	return nil
}

type CreateRecepieRequest struct {
	Recepie              *Recepie `protobuf:"bytes,1,opt,name=recepie,proto3" json:"recepie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRecepieRequest) Reset()         { *m = CreateRecepieRequest{} }
func (m *CreateRecepieRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRecepieRequest) ProtoMessage()    {}
func (*CreateRecepieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_9d90ce52d6af1e66, []int{2}
}
func (m *CreateRecepieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRecepieRequest.Unmarshal(m, b)
}
func (m *CreateRecepieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRecepieRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRecepieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRecepieRequest.Merge(dst, src)
}
func (m *CreateRecepieRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRecepieRequest.Size(m)
}
func (m *CreateRecepieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRecepieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRecepieRequest proto.InternalMessageInfo

func (m *CreateRecepieRequest) GetRecepie() *Recepie {
	if m != nil {
		return m.Recepie
	}
	return nil
}

type CreateRecepieResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRecepieResponse) Reset()         { *m = CreateRecepieResponse{} }
func (m *CreateRecepieResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRecepieResponse) ProtoMessage()    {}
func (*CreateRecepieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_9d90ce52d6af1e66, []int{3}
}
func (m *CreateRecepieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRecepieResponse.Unmarshal(m, b)
}
func (m *CreateRecepieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRecepieResponse.Marshal(b, m, deterministic)
}
func (dst *CreateRecepieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRecepieResponse.Merge(dst, src)
}
func (m *CreateRecepieResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRecepieResponse.Size(m)
}
func (m *CreateRecepieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRecepieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRecepieResponse proto.InternalMessageInfo

func (m *CreateRecepieResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateRecepieRequest struct {
	Recepie              *Recepie `protobuf:"bytes,1,opt,name=recepie,proto3" json:"recepie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRecepieRequest) Reset()         { *m = UpdateRecepieRequest{} }
func (m *UpdateRecepieRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRecepieRequest) ProtoMessage()    {}
func (*UpdateRecepieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_9d90ce52d6af1e66, []int{4}
}
func (m *UpdateRecepieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRecepieRequest.Unmarshal(m, b)
}
func (m *UpdateRecepieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRecepieRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRecepieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRecepieRequest.Merge(dst, src)
}
func (m *UpdateRecepieRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRecepieRequest.Size(m)
}
func (m *UpdateRecepieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRecepieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRecepieRequest proto.InternalMessageInfo

func (m *UpdateRecepieRequest) GetRecepie() *Recepie {
	if m != nil {
		return m.Recepie
	}
	return nil
}

type UpdateRecepieResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRecepieResponse) Reset()         { *m = UpdateRecepieResponse{} }
func (m *UpdateRecepieResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRecepieResponse) ProtoMessage()    {}
func (*UpdateRecepieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_9d90ce52d6af1e66, []int{5}
}
func (m *UpdateRecepieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRecepieResponse.Unmarshal(m, b)
}
func (m *UpdateRecepieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRecepieResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateRecepieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRecepieResponse.Merge(dst, src)
}
func (m *UpdateRecepieResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRecepieResponse.Size(m)
}
func (m *UpdateRecepieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRecepieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRecepieResponse proto.InternalMessageInfo

type DeleteRecepieRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRecepieRequest) Reset()         { *m = DeleteRecepieRequest{} }
func (m *DeleteRecepieRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRecepieRequest) ProtoMessage()    {}
func (*DeleteRecepieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_9d90ce52d6af1e66, []int{6}
}
func (m *DeleteRecepieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRecepieRequest.Unmarshal(m, b)
}
func (m *DeleteRecepieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRecepieRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRecepieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRecepieRequest.Merge(dst, src)
}
func (m *DeleteRecepieRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRecepieRequest.Size(m)
}
func (m *DeleteRecepieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRecepieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRecepieRequest proto.InternalMessageInfo

func (m *DeleteRecepieRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteRecepieResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRecepieResponse) Reset()         { *m = DeleteRecepieResponse{} }
func (m *DeleteRecepieResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRecepieResponse) ProtoMessage()    {}
func (*DeleteRecepieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_9d90ce52d6af1e66, []int{7}
}
func (m *DeleteRecepieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRecepieResponse.Unmarshal(m, b)
}
func (m *DeleteRecepieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRecepieResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteRecepieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRecepieResponse.Merge(dst, src)
}
func (m *DeleteRecepieResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRecepieResponse.Size(m)
}
func (m *DeleteRecepieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRecepieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRecepieResponse proto.InternalMessageInfo

type ListRecepieRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRecepieRequest) Reset()         { *m = ListRecepieRequest{} }
func (m *ListRecepieRequest) String() string { return proto.CompactTextString(m) }
func (*ListRecepieRequest) ProtoMessage()    {}
func (*ListRecepieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_9d90ce52d6af1e66, []int{8}
}
func (m *ListRecepieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecepieRequest.Unmarshal(m, b)
}
func (m *ListRecepieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecepieRequest.Marshal(b, m, deterministic)
}
func (dst *ListRecepieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecepieRequest.Merge(dst, src)
}
func (m *ListRecepieRequest) XXX_Size() int {
	return xxx_messageInfo_ListRecepieRequest.Size(m)
}
func (m *ListRecepieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecepieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecepieRequest proto.InternalMessageInfo

type ListRecepieResponse struct {
	Recepies             []*Recepie `protobuf:"bytes,1,rep,name=recepies,proto3" json:"recepies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListRecepieResponse) Reset()         { *m = ListRecepieResponse{} }
func (m *ListRecepieResponse) String() string { return proto.CompactTextString(m) }
func (*ListRecepieResponse) ProtoMessage()    {}
func (*ListRecepieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_9d90ce52d6af1e66, []int{9}
}
func (m *ListRecepieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecepieResponse.Unmarshal(m, b)
}
func (m *ListRecepieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecepieResponse.Marshal(b, m, deterministic)
}
func (dst *ListRecepieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecepieResponse.Merge(dst, src)
}
func (m *ListRecepieResponse) XXX_Size() int {
	return xxx_messageInfo_ListRecepieResponse.Size(m)
}
func (m *ListRecepieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecepieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecepieResponse proto.InternalMessageInfo

func (m *ListRecepieResponse) GetRecepies() []*Recepie {
	if m != nil {
		return m.Recepies
	}
	return nil
}

type Quantity struct {
	Volume               float32  `protobuf:"fixed32,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Unit                 Unit     `protobuf:"varint,2,opt,name=unit,proto3,enum=brewmmer.Unit" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quantity) Reset()         { *m = Quantity{} }
func (m *Quantity) String() string { return proto.CompactTextString(m) }
func (*Quantity) ProtoMessage()    {}
func (*Quantity) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_9d90ce52d6af1e66, []int{10}
}
func (m *Quantity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quantity.Unmarshal(m, b)
}
func (m *Quantity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quantity.Marshal(b, m, deterministic)
}
func (dst *Quantity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quantity.Merge(dst, src)
}
func (m *Quantity) XXX_Size() int {
	return xxx_messageInfo_Quantity.Size(m)
}
func (m *Quantity) XXX_DiscardUnknown() {
	xxx_messageInfo_Quantity.DiscardUnknown(m)
}

var xxx_messageInfo_Quantity proto.InternalMessageInfo

func (m *Quantity) GetVolume() float32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Quantity) GetUnit() Unit {
	if m != nil {
		return m.Unit
	}
	return Unit_NULL_UNIT
}

type Ingredient struct {
	Type                 IngredientType `protobuf:"varint,1,opt,name=type,proto3,enum=brewmmer.IngredientType" json:"type,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity             *Quantity      `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Ingredient) Reset()         { *m = Ingredient{} }
func (m *Ingredient) String() string { return proto.CompactTextString(m) }
func (*Ingredient) ProtoMessage()    {}
func (*Ingredient) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_9d90ce52d6af1e66, []int{11}
}
func (m *Ingredient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ingredient.Unmarshal(m, b)
}
func (m *Ingredient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ingredient.Marshal(b, m, deterministic)
}
func (dst *Ingredient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ingredient.Merge(dst, src)
}
func (m *Ingredient) XXX_Size() int {
	return xxx_messageInfo_Ingredient.Size(m)
}
func (m *Ingredient) XXX_DiscardUnknown() {
	xxx_messageInfo_Ingredient.DiscardUnknown(m)
}

var xxx_messageInfo_Ingredient proto.InternalMessageInfo

func (m *Ingredient) GetType() IngredientType {
	if m != nil {
		return m.Type
	}
	return IngredientType_NULL_INGREDIENT_TYPE
}

func (m *Ingredient) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ingredient) GetQuantity() *Quantity {
	if m != nil {
		return m.Quantity
	}
	return nil
}

type Step struct {
	Phase                Phase         `protobuf:"varint,1,opt,name=phase,proto3,enum=brewmmer.Phase" json:"phase,omitempty"`
	Temperature          int32         `protobuf:"varint,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Duration             *Quantity     `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Ingredients          []*Ingredient `protobuf:"bytes,4,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_9d90ce52d6af1e66, []int{12}
}
func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (dst *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(dst, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetPhase() Phase {
	if m != nil {
		return m.Phase
	}
	return Phase_INIT
}

func (m *Step) GetTemperature() int32 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

func (m *Step) GetDuration() *Quantity {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *Step) GetIngredients() []*Ingredient {
	if m != nil {
		return m.Ingredients
	}
	return nil
}

type Recepie struct {
	Id                   int32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Ingredients          []*Ingredient `protobuf:"bytes,4,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	Steps                []*Step       `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Recepie) Reset()         { *m = Recepie{} }
func (m *Recepie) String() string { return proto.CompactTextString(m) }
func (*Recepie) ProtoMessage()    {}
func (*Recepie) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_9d90ce52d6af1e66, []int{13}
}
func (m *Recepie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recepie.Unmarshal(m, b)
}
func (m *Recepie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recepie.Marshal(b, m, deterministic)
}
func (dst *Recepie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recepie.Merge(dst, src)
}
func (m *Recepie) XXX_Size() int {
	return xxx_messageInfo_Recepie.Size(m)
}
func (m *Recepie) XXX_DiscardUnknown() {
	xxx_messageInfo_Recepie.DiscardUnknown(m)
}

var xxx_messageInfo_Recepie proto.InternalMessageInfo

func (m *Recepie) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Recepie) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Recepie) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Recepie) GetIngredients() []*Ingredient {
	if m != nil {
		return m.Ingredients
	}
	return nil
}

func (m *Recepie) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRecepieRequest)(nil), "brewmmer.GetRecepieRequest")
	proto.RegisterType((*GetRecepieResponse)(nil), "brewmmer.GetRecepieResponse")
	proto.RegisterType((*CreateRecepieRequest)(nil), "brewmmer.CreateRecepieRequest")
	proto.RegisterType((*CreateRecepieResponse)(nil), "brewmmer.CreateRecepieResponse")
	proto.RegisterType((*UpdateRecepieRequest)(nil), "brewmmer.UpdateRecepieRequest")
	proto.RegisterType((*UpdateRecepieResponse)(nil), "brewmmer.UpdateRecepieResponse")
	proto.RegisterType((*DeleteRecepieRequest)(nil), "brewmmer.DeleteRecepieRequest")
	proto.RegisterType((*DeleteRecepieResponse)(nil), "brewmmer.DeleteRecepieResponse")
	proto.RegisterType((*ListRecepieRequest)(nil), "brewmmer.ListRecepieRequest")
	proto.RegisterType((*ListRecepieResponse)(nil), "brewmmer.ListRecepieResponse")
	proto.RegisterType((*Quantity)(nil), "brewmmer.Quantity")
	proto.RegisterType((*Ingredient)(nil), "brewmmer.Ingredient")
	proto.RegisterType((*Step)(nil), "brewmmer.Step")
	proto.RegisterType((*Recepie)(nil), "brewmmer.Recepie")
	proto.RegisterEnum("brewmmer.IngredientType", IngredientType_name, IngredientType_value)
	proto.RegisterEnum("brewmmer.Unit", Unit_name, Unit_value)
	proto.RegisterEnum("brewmmer.Phase", Phase_name, Phase_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecepieServiceClient is the client API for RecepieService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecepieServiceClient interface {
	Get(ctx context.Context, in *GetRecepieRequest, opts ...grpc.CallOption) (*GetRecepieResponse, error)
	Create(ctx context.Context, in *CreateRecepieRequest, opts ...grpc.CallOption) (*CreateRecepieResponse, error)
	Update(ctx context.Context, in *UpdateRecepieRequest, opts ...grpc.CallOption) (*UpdateRecepieResponse, error)
	Delete(ctx context.Context, in *DeleteRecepieRequest, opts ...grpc.CallOption) (*DeleteRecepieResponse, error)
	List(ctx context.Context, in *ListRecepieRequest, opts ...grpc.CallOption) (*ListRecepieResponse, error)
}

type recepieServiceClient struct {
	cc *grpc.ClientConn
}

func NewRecepieServiceClient(cc *grpc.ClientConn) RecepieServiceClient {
	return &recepieServiceClient{cc}
}

func (c *recepieServiceClient) Get(ctx context.Context, in *GetRecepieRequest, opts ...grpc.CallOption) (*GetRecepieResponse, error) {
	out := new(GetRecepieResponse)
	err := c.cc.Invoke(ctx, "/brewmmer.RecepieService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recepieServiceClient) Create(ctx context.Context, in *CreateRecepieRequest, opts ...grpc.CallOption) (*CreateRecepieResponse, error) {
	out := new(CreateRecepieResponse)
	err := c.cc.Invoke(ctx, "/brewmmer.RecepieService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recepieServiceClient) Update(ctx context.Context, in *UpdateRecepieRequest, opts ...grpc.CallOption) (*UpdateRecepieResponse, error) {
	out := new(UpdateRecepieResponse)
	err := c.cc.Invoke(ctx, "/brewmmer.RecepieService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recepieServiceClient) Delete(ctx context.Context, in *DeleteRecepieRequest, opts ...grpc.CallOption) (*DeleteRecepieResponse, error) {
	out := new(DeleteRecepieResponse)
	err := c.cc.Invoke(ctx, "/brewmmer.RecepieService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recepieServiceClient) List(ctx context.Context, in *ListRecepieRequest, opts ...grpc.CallOption) (*ListRecepieResponse, error) {
	out := new(ListRecepieResponse)
	err := c.cc.Invoke(ctx, "/brewmmer.RecepieService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecepieServiceServer is the server API for RecepieService service.
type RecepieServiceServer interface {
	Get(context.Context, *GetRecepieRequest) (*GetRecepieResponse, error)
	Create(context.Context, *CreateRecepieRequest) (*CreateRecepieResponse, error)
	Update(context.Context, *UpdateRecepieRequest) (*UpdateRecepieResponse, error)
	Delete(context.Context, *DeleteRecepieRequest) (*DeleteRecepieResponse, error)
	List(context.Context, *ListRecepieRequest) (*ListRecepieResponse, error)
}

func RegisterRecepieServiceServer(s *grpc.Server, srv RecepieServiceServer) {
	s.RegisterService(&_RecepieService_serviceDesc, srv)
}

func _RecepieService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecepieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecepieServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/brewmmer.RecepieService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecepieServiceServer).Get(ctx, req.(*GetRecepieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecepieService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecepieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecepieServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/brewmmer.RecepieService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecepieServiceServer).Create(ctx, req.(*CreateRecepieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecepieService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRecepieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecepieServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/brewmmer.RecepieService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecepieServiceServer).Update(ctx, req.(*UpdateRecepieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecepieService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRecepieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecepieServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/brewmmer.RecepieService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecepieServiceServer).Delete(ctx, req.(*DeleteRecepieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecepieService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecepieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecepieServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/brewmmer.RecepieService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecepieServiceServer).List(ctx, req.(*ListRecepieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RecepieService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "brewmmer.RecepieService",
	HandlerType: (*RecepieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _RecepieService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _RecepieService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _RecepieService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RecepieService_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _RecepieService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/brewmmer/recepie.proto",
}

func init() { proto.RegisterFile("api/brewmmer/recepie.proto", fileDescriptor_recepie_9d90ce52d6af1e66) }

var fileDescriptor_recepie_9d90ce52d6af1e66 = []byte{
	// 710 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4b, 0x6f, 0xda, 0x4c,
	0x14, 0x8d, 0x5f, 0x3c, 0x2e, 0xf9, 0xf8, 0x26, 0xb7, 0xa4, 0xb1, 0xe8, 0x0b, 0xb9, 0xaf, 0x28,
	0x6d, 0x89, 0x44, 0xa5, 0xee, 0x2a, 0x95, 0x00, 0x21, 0x56, 0xc1, 0xd0, 0xc1, 0xa8, 0xca, 0x2a,
	0x22, 0x61, 0x94, 0x5a, 0x0a, 0xc6, 0xb1, 0x87, 0x54, 0xd9, 0xf4, 0x1f, 0x75, 0xdd, 0xbf, 0xd6,
	0x65, 0x35, 0xb6, 0xc1, 0x0e, 0x71, 0x2a, 0xb5, 0x5d, 0x31, 0x33, 0xe7, 0xcc, 0x99, 0x33, 0xf7,
	0x0e, 0xc7, 0x50, 0x9d, 0x78, 0xce, 0xfe, 0xa9, 0xcf, 0xbe, 0xce, 0x66, 0xcc, 0xdf, 0xf7, 0xd9,
	0x19, 0xf3, 0x1c, 0x56, 0xf7, 0xfc, 0x39, 0x9f, 0x63, 0x61, 0xb9, 0x6e, 0x3c, 0x85, 0xad, 0x2e,
	0xe3, 0x34, 0x42, 0x29, 0xbb, 0x5c, 0xb0, 0x80, 0x63, 0x19, 0x64, 0x67, 0xaa, 0x4b, 0x35, 0x69,
	0x57, 0xa1, 0xb2, 0x33, 0x35, 0x9a, 0x80, 0x69, 0x52, 0xe0, 0xcd, 0xdd, 0x80, 0xe1, 0x2b, 0xc8,
	0xc7, 0xaa, 0x21, 0xb5, 0xd4, 0xd8, 0xaa, 0x2f, 0x65, 0xeb, 0x4b, 0xee, 0x92, 0x61, 0xb4, 0xa0,
	0xd2, 0xf2, 0xd9, 0x84, 0xb3, 0xb5, 0xa3, 0xfe, 0x48, 0xe4, 0x25, 0x6c, 0xaf, 0x89, 0xc4, 0x56,
	0xd6, 0x0d, 0xb7, 0xa0, 0x32, 0xf6, 0xa6, 0xff, 0x78, 0xda, 0x0e, 0x6c, 0xaf, 0x89, 0x44, 0xa7,
	0x19, 0x2f, 0xa0, 0xd2, 0x66, 0x17, 0xec, 0x96, 0xfa, 0xba, 0x8b, 0x1d, 0xd8, 0x5e, 0xe3, 0xc5,
	0x02, 0x15, 0xc0, 0x9e, 0x13, 0xac, 0x55, 0xdd, 0x68, 0xc3, 0xbd, 0x1b, 0xab, 0xf1, 0xdd, 0xde,
	0x40, 0x21, 0x76, 0x14, 0xe8, 0x52, 0x4d, 0xc9, 0x36, 0xbd, 0xa2, 0x18, 0x87, 0x50, 0xf8, 0xb4,
	0x98, 0xb8, 0xdc, 0xe1, 0xd7, 0x78, 0x1f, 0x72, 0x57, 0xf3, 0x8b, 0xc5, 0x2c, 0xba, 0xad, 0x4c,
	0xe3, 0x19, 0x1a, 0xa0, 0x2e, 0x5c, 0x87, 0xeb, 0x72, 0x4d, 0xda, 0x2d, 0x37, 0xca, 0x89, 0xdc,
	0xd8, 0x75, 0x38, 0x0d, 0x31, 0xe3, 0x1b, 0x80, 0xe9, 0x9e, 0xfb, 0x6c, 0xea, 0x30, 0x97, 0xe3,
	0x6b, 0x50, 0xf9, 0xb5, 0x17, 0xe9, 0x94, 0x1b, 0x7a, 0xb2, 0x23, 0xe1, 0xd8, 0xd7, 0x1e, 0xa3,
	0x21, 0x0b, 0x11, 0x54, 0x77, 0x32, 0x63, 0xa1, 0x7e, 0x91, 0x86, 0x63, 0xac, 0x43, 0xe1, 0x32,
	0xf6, 0xa5, 0x2b, 0x61, 0xed, 0x31, 0x51, 0x59, 0x3a, 0xa6, 0x2b, 0x8e, 0xf1, 0x43, 0x02, 0x75,
	0xc4, 0x99, 0x87, 0xcf, 0x41, 0xf3, 0xbe, 0x4c, 0x82, 0xe5, 0xd9, 0xff, 0x27, 0xbb, 0x86, 0x62,
	0x99, 0x46, 0x28, 0xd6, 0xa0, 0xc4, 0xd9, 0xcc, 0x63, 0xfe, 0x84, 0x2f, 0xfc, 0xe8, 0x68, 0x8d,
	0xa6, 0x97, 0x84, 0x83, 0xe9, 0xc2, 0x9f, 0x70, 0x67, 0xee, 0xfe, 0xce, 0xc1, 0x92, 0x83, 0xef,
	0xa0, 0xe4, 0xac, 0x6e, 0x17, 0xe8, 0x6a, 0x58, 0xfb, 0x4a, 0xd6, 0xd5, 0x69, 0x9a, 0x68, 0x7c,
	0x97, 0x20, 0x1f, 0xf7, 0x25, 0xf5, 0x24, 0x34, 0xf1, 0x24, 0x32, 0x2b, 0x53, 0x83, 0xd2, 0x94,
	0x05, 0x67, 0xbe, 0xe3, 0xad, 0xac, 0x15, 0x69, 0x7a, 0xe9, 0x6f, 0x9d, 0xe0, 0x33, 0xd0, 0x02,
	0xce, 0xbc, 0x40, 0xd7, 0xc2, 0x1d, 0xa9, 0x46, 0x8b, 0xca, 0xd2, 0x08, 0xdc, 0xb3, 0xa1, 0x7c,
	0xb3, 0x8b, 0xa8, 0x43, 0xc5, 0x1a, 0xf7, 0x7a, 0x27, 0xa6, 0xd5, 0xa5, 0x9d, 0xb6, 0xd9, 0xb1,
	0xec, 0x13, 0xfb, 0x78, 0xd8, 0x21, 0x1b, 0x58, 0x04, 0xed, 0x73, 0xd3, 0xee, 0x50, 0x22, 0x61,
	0x01, 0xd4, 0x7e, 0xb3, 0x67, 0x13, 0x59, 0x8c, 0x8e, 0x06, 0xc3, 0x11, 0x51, 0x04, 0x7c, 0x6c,
	0x76, 0x46, 0x36, 0x51, 0xf7, 0xde, 0x83, 0x2a, 0x5e, 0x13, 0xfe, 0x07, 0xc5, 0x50, 0x6b, 0x6c,
	0x99, 0x36, 0xd9, 0x40, 0x0d, 0xa4, 0x1e, 0x91, 0xc4, 0x4f, 0x97, 0xc8, 0x98, 0x03, 0xf9, 0x63,
	0x97, 0x28, 0x98, 0x07, 0xa5, 0x6f, 0x5a, 0x44, 0x15, 0x83, 0x76, 0xf3, 0x98, 0x68, 0x7b, 0xe7,
	0xa0, 0x85, 0xed, 0x15, 0xe2, 0x66, 0xb4, 0xb5, 0x04, 0xf9, 0x7e, 0x73, 0x74, 0x64, 0x5a, 0x5d,
	0x22, 0x89, 0xc9, 0xc1, 0xc0, 0xec, 0x89, 0x89, 0x8c, 0x9b, 0x50, 0x18, 0x0d, 0x9b, 0xb4, 0x2b,
	0x66, 0x8a, 0x98, 0xb5, 0x8e, 0xcc, 0x5e, 0x88, 0xa9, 0x48, 0x60, 0xf3, 0xb0, 0x43, 0xfb, 0x1d,
	0xcb, 0x6e, 0xda, 0xe6, 0xc0, 0x22, 0x9a, 0xc0, 0x0f, 0x06, 0xb6, 0x1d, 0xe2, 0xb9, 0xc6, 0x4f,
	0x19, 0xca, 0x71, 0xb7, 0x46, 0xcc, 0xbf, 0x72, 0xce, 0x18, 0x7e, 0x00, 0xa5, 0xcb, 0x38, 0x3e,
	0x48, 0xca, 0x75, 0x2b, 0x22, 0xab, 0x0f, 0xb3, 0xc1, 0xf8, 0x3f, 0x6b, 0x42, 0x2e, 0x0a, 0x2a,
	0x7c, 0x9c, 0xf0, 0xb2, 0xf2, 0xaf, 0xfa, 0xe4, 0x4e, 0x3c, 0x91, 0x8a, 0x52, 0x28, 0x2d, 0x95,
	0x15, 0x6e, 0x69, 0xa9, 0xcc, 0xdc, 0x12, 0x52, 0x51, 0x1e, 0xa5, 0xa5, 0xb2, 0x92, 0x2c, 0x2d,
	0x95, 0x99, 0x60, 0xd8, 0x02, 0x55, 0x64, 0x15, 0xa6, 0xca, 0x70, 0x3b, 0xd1, 0xaa, 0x8f, 0xee,
	0x40, 0x23, 0x91, 0xd3, 0x5c, 0xf8, 0x31, 0x7a, 0xfb, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x5a, 0xad,
	0x0c, 0x31, 0xaa, 0x06, 0x00, 0x00,
}
