// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/recepie/recepie.proto

package recepie

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IngredientType int32

const (
	IngredientType_NULL_INGREDIENT_TYPE IngredientType = 0
	IngredientType_WATER                IngredientType = 1
	IngredientType_MALT                 IngredientType = 2
	IngredientType_HOPS                 IngredientType = 3
	IngredientType_YIEST                IngredientType = 4
)

var IngredientType_name = map[int32]string{
	0: "NULL_INGREDIENT_TYPE",
	1: "WATER",
	2: "MALT",
	3: "HOPS",
	4: "YIEST",
}
var IngredientType_value = map[string]int32{
	"NULL_INGREDIENT_TYPE": 0,
	"WATER":                1,
	"MALT":                 2,
	"HOPS":                 3,
	"YIEST":                4,
}

func (x IngredientType) String() string {
	return proto.EnumName(IngredientType_name, int32(x))
}
func (IngredientType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_recepie_a0e3b1a1eed1346f, []int{0}
}

type Unit int32

const (
	Unit_NULL_UNIT Unit = 0
	Unit_L         Unit = 1
	Unit_G         Unit = 2
	Unit_KG        Unit = 3
	Unit_MIN       Unit = 4
	Unit_DAY       Unit = 5
)

var Unit_name = map[int32]string{
	0: "NULL_UNIT",
	1: "L",
	2: "G",
	3: "KG",
	4: "MIN",
	5: "DAY",
}
var Unit_value = map[string]int32{
	"NULL_UNIT": 0,
	"L":         1,
	"G":         2,
	"KG":        3,
	"MIN":       4,
	"DAY":       5,
}

func (x Unit) String() string {
	return proto.EnumName(Unit_name, int32(x))
}
func (Unit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_recepie_a0e3b1a1eed1346f, []int{1}
}

type Phase int32

const (
	Phase_INIT         Phase = 0
	Phase_MASHING      Phase = 1
	Phase_BOILING      Phase = 2
	Phase_SPARGING     Phase = 3
	Phase_CHILLING     Phase = 4
	Phase_FERMENTATION Phase = 5
	Phase_BOTTLING     Phase = 6
)

var Phase_name = map[int32]string{
	0: "INIT",
	1: "MASHING",
	2: "BOILING",
	3: "SPARGING",
	4: "CHILLING",
	5: "FERMENTATION",
	6: "BOTTLING",
}
var Phase_value = map[string]int32{
	"INIT":         0,
	"MASHING":      1,
	"BOILING":      2,
	"SPARGING":     3,
	"CHILLING":     4,
	"FERMENTATION": 5,
	"BOTTLING":     6,
}

func (x Phase) String() string {
	return proto.EnumName(Phase_name, int32(x))
}
func (Phase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_recepie_a0e3b1a1eed1346f, []int{2}
}

type GetRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_a0e3b1a1eed1346f, []int{0}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetResponse struct {
	Recepie              *Recepie `protobuf:"bytes,1,opt,name=recepie,proto3" json:"recepie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_a0e3b1a1eed1346f, []int{1}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetRecepie() *Recepie {
	if m != nil {
		return m.Recepie
	}
	return nil
}

type CreateRequest struct {
	Recepie              *Recepie `protobuf:"bytes,1,opt,name=recepie,proto3" json:"recepie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_a0e3b1a1eed1346f, []int{2}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetRecepie() *Recepie {
	if m != nil {
		return m.Recepie
	}
	return nil
}

type CreateResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_a0e3b1a1eed1346f, []int{3}
}
func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (dst *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(dst, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateRequest struct {
	Recepie              *Recepie `protobuf:"bytes,1,opt,name=recepie,proto3" json:"recepie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_a0e3b1a1eed1346f, []int{4}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(dst, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetRecepie() *Recepie {
	if m != nil {
		return m.Recepie
	}
	return nil
}

type DeleteRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_a0e3b1a1eed1346f, []int{5}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListResponse struct {
	Recepies             []*Recepie `protobuf:"bytes,1,rep,name=recepies,proto3" json:"recepies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_a0e3b1a1eed1346f, []int{6}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetRecepies() []*Recepie {
	if m != nil {
		return m.Recepies
	}
	return nil
}

type Quantity struct {
	Volume               float32  `protobuf:"fixed32,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Unit                 Unit     `protobuf:"varint,2,opt,name=unit,proto3,enum=recepie.Unit" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quantity) Reset()         { *m = Quantity{} }
func (m *Quantity) String() string { return proto.CompactTextString(m) }
func (*Quantity) ProtoMessage()    {}
func (*Quantity) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_a0e3b1a1eed1346f, []int{7}
}
func (m *Quantity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quantity.Unmarshal(m, b)
}
func (m *Quantity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quantity.Marshal(b, m, deterministic)
}
func (dst *Quantity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quantity.Merge(dst, src)
}
func (m *Quantity) XXX_Size() int {
	return xxx_messageInfo_Quantity.Size(m)
}
func (m *Quantity) XXX_DiscardUnknown() {
	xxx_messageInfo_Quantity.DiscardUnknown(m)
}

var xxx_messageInfo_Quantity proto.InternalMessageInfo

func (m *Quantity) GetVolume() float32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Quantity) GetUnit() Unit {
	if m != nil {
		return m.Unit
	}
	return Unit_NULL_UNIT
}

type Ingredient struct {
	Type                 IngredientType `protobuf:"varint,1,opt,name=type,proto3,enum=recepie.IngredientType" json:"type,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity             *Quantity      `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Ingredient) Reset()         { *m = Ingredient{} }
func (m *Ingredient) String() string { return proto.CompactTextString(m) }
func (*Ingredient) ProtoMessage()    {}
func (*Ingredient) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_a0e3b1a1eed1346f, []int{8}
}
func (m *Ingredient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ingredient.Unmarshal(m, b)
}
func (m *Ingredient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ingredient.Marshal(b, m, deterministic)
}
func (dst *Ingredient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ingredient.Merge(dst, src)
}
func (m *Ingredient) XXX_Size() int {
	return xxx_messageInfo_Ingredient.Size(m)
}
func (m *Ingredient) XXX_DiscardUnknown() {
	xxx_messageInfo_Ingredient.DiscardUnknown(m)
}

var xxx_messageInfo_Ingredient proto.InternalMessageInfo

func (m *Ingredient) GetType() IngredientType {
	if m != nil {
		return m.Type
	}
	return IngredientType_NULL_INGREDIENT_TYPE
}

func (m *Ingredient) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ingredient) GetQuantity() *Quantity {
	if m != nil {
		return m.Quantity
	}
	return nil
}

type Step struct {
	Phase                Phase         `protobuf:"varint,1,opt,name=phase,proto3,enum=recepie.Phase" json:"phase,omitempty"`
	Temperature          int32         `protobuf:"varint,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Duration             *Quantity     `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Ingredients          []*Ingredient `protobuf:"bytes,4,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_a0e3b1a1eed1346f, []int{9}
}
func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (dst *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(dst, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetPhase() Phase {
	if m != nil {
		return m.Phase
	}
	return Phase_INIT
}

func (m *Step) GetTemperature() int32 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

func (m *Step) GetDuration() *Quantity {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *Step) GetIngredients() []*Ingredient {
	if m != nil {
		return m.Ingredients
	}
	return nil
}

type Recepie struct {
	Uuid                 int32         `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Ingredients          []*Ingredient `protobuf:"bytes,4,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	Steps                []*Step       `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Recepie) Reset()         { *m = Recepie{} }
func (m *Recepie) String() string { return proto.CompactTextString(m) }
func (*Recepie) ProtoMessage()    {}
func (*Recepie) Descriptor() ([]byte, []int) {
	return fileDescriptor_recepie_a0e3b1a1eed1346f, []int{10}
}
func (m *Recepie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recepie.Unmarshal(m, b)
}
func (m *Recepie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recepie.Marshal(b, m, deterministic)
}
func (dst *Recepie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recepie.Merge(dst, src)
}
func (m *Recepie) XXX_Size() int {
	return xxx_messageInfo_Recepie.Size(m)
}
func (m *Recepie) XXX_DiscardUnknown() {
	xxx_messageInfo_Recepie.DiscardUnknown(m)
}

var xxx_messageInfo_Recepie proto.InternalMessageInfo

func (m *Recepie) GetUuid() int32 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *Recepie) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Recepie) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Recepie) GetIngredients() []*Ingredient {
	if m != nil {
		return m.Ingredients
	}
	return nil
}

func (m *Recepie) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "recepie.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "recepie.GetResponse")
	proto.RegisterType((*CreateRequest)(nil), "recepie.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "recepie.CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "recepie.UpdateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "recepie.DeleteRequest")
	proto.RegisterType((*ListResponse)(nil), "recepie.ListResponse")
	proto.RegisterType((*Quantity)(nil), "recepie.Quantity")
	proto.RegisterType((*Ingredient)(nil), "recepie.Ingredient")
	proto.RegisterType((*Step)(nil), "recepie.Step")
	proto.RegisterType((*Recepie)(nil), "recepie.Recepie")
	proto.RegisterEnum("recepie.IngredientType", IngredientType_name, IngredientType_value)
	proto.RegisterEnum("recepie.Unit", Unit_name, Unit_value)
	proto.RegisterEnum("recepie.Phase", Phase_name, Phase_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecepieServiceClient is the client API for RecepieService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecepieServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListResponse, error)
}

type recepieServiceClient struct {
	cc *grpc.ClientConn
}

func NewRecepieServiceClient(cc *grpc.ClientConn) RecepieServiceClient {
	return &recepieServiceClient{cc}
}

func (c *recepieServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/recepie.RecepieService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recepieServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/recepie.RecepieService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recepieServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/recepie.RecepieService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recepieServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/recepie.RecepieService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recepieServiceClient) List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/recepie.RecepieService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecepieServiceServer is the server API for RecepieService service.
type RecepieServiceServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Update(context.Context, *UpdateRequest) (*empty.Empty, error)
	Delete(context.Context, *DeleteRequest) (*empty.Empty, error)
	List(context.Context, *empty.Empty) (*ListResponse, error)
}

func RegisterRecepieServiceServer(s *grpc.Server, srv RecepieServiceServer) {
	s.RegisterService(&_RecepieService_serviceDesc, srv)
}

func _RecepieService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecepieServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recepie.RecepieService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecepieServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecepieService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecepieServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recepie.RecepieService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecepieServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecepieService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecepieServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recepie.RecepieService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecepieServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecepieService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecepieServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recepie.RecepieService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecepieServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecepieService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecepieServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recepie.RecepieService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecepieServiceServer).List(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _RecepieService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recepie.RecepieService",
	HandlerType: (*RecepieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _RecepieService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _RecepieService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _RecepieService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RecepieService_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _RecepieService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/recepie/recepie.proto",
}

func init() { proto.RegisterFile("api/recepie/recepie.proto", fileDescriptor_recepie_a0e3b1a1eed1346f) }

var fileDescriptor_recepie_a0e3b1a1eed1346f = []byte{
	// 704 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4b, 0x6f, 0xd3, 0x4a,
	0x14, 0xae, 0x5f, 0x79, 0x9c, 0x34, 0xd1, 0xdc, 0xb9, 0xbd, 0x6d, 0x6e, 0x40, 0x22, 0x04, 0x16,
	0x55, 0x80, 0x14, 0x05, 0x55, 0xa2, 0x2a, 0x2c, 0xd2, 0xd6, 0xa4, 0x16, 0x8e, 0x13, 0x26, 0x8e,
	0x50, 0x57, 0x95, 0xdb, 0x0c, 0xc1, 0x52, 0x63, 0xbb, 0xf6, 0xb8, 0x52, 0x24, 0x7e, 0x10, 0x3b,
	0x36, 0xfc, 0x40, 0x34, 0xe3, 0x47, 0x92, 0xd2, 0x22, 0xd1, 0xd5, 0xcc, 0x79, 0x7c, 0xdf, 0x39,
	0x73, 0x8e, 0xfd, 0xc1, 0xff, 0x4e, 0xe0, 0xee, 0x85, 0xf4, 0x92, 0x06, 0x2e, 0xcd, 0xce, 0x4e,
	0x10, 0xfa, 0xcc, 0xc7, 0xc5, 0xd4, 0x6c, 0x3c, 0x9a, 0xf9, 0xfe, 0xec, 0x8a, 0xee, 0x09, 0xf7,
	0x45, 0xfc, 0x65, 0x8f, 0xce, 0x03, 0xb6, 0x48, 0xb2, 0x5a, 0x8f, 0x01, 0xfa, 0x94, 0x11, 0x7a,
	0x1d, 0xd3, 0x88, 0xe1, 0x1a, 0xc8, 0xee, 0xb4, 0x2e, 0x35, 0xa5, 0x5d, 0x85, 0xc8, 0xee, 0xb4,
	0x75, 0x00, 0x15, 0x11, 0x8d, 0x02, 0xdf, 0x8b, 0x28, 0x6e, 0x43, 0x46, 0x2a, 0x72, 0x2a, 0x5d,
	0xd4, 0xc9, 0x6a, 0x92, 0xe4, 0x24, 0x59, 0x42, 0xeb, 0x10, 0xaa, 0xc7, 0x21, 0x75, 0x18, 0xcd,
	0xb8, 0xff, 0x06, 0xdc, 0x84, 0x5a, 0x06, 0x4e, 0x4b, 0xdf, 0xee, 0xec, 0x10, 0xaa, 0x93, 0x60,
	0xfa, 0x40, 0xfa, 0x27, 0x50, 0x3d, 0xa1, 0x57, 0x74, 0x09, 0xbe, 0xcd, 0xfe, 0x0e, 0x36, 0x4d,
	0x37, 0x5a, 0x3e, 0xfc, 0x25, 0x94, 0x52, 0x6c, 0x54, 0x97, 0x9a, 0xca, 0x9d, 0xec, 0x79, 0x46,
	0x4b, 0x87, 0xd2, 0xa7, 0xd8, 0xf1, 0x98, 0xcb, 0x16, 0x78, 0x1b, 0x0a, 0x37, 0xfe, 0x55, 0x3c,
	0x4f, 0xba, 0x92, 0x49, 0x6a, 0xe1, 0xa7, 0xa0, 0xc6, 0x9e, 0xcb, 0xea, 0x72, 0x53, 0xda, 0xad,
	0x75, 0xab, 0x39, 0xdb, 0xc4, 0x73, 0x19, 0x11, 0xa1, 0xd6, 0x37, 0x00, 0xc3, 0x9b, 0x85, 0x74,
	0xea, 0x52, 0x8f, 0xe1, 0x17, 0xa0, 0xb2, 0x45, 0x90, 0xd0, 0xd4, 0xba, 0x3b, 0x39, 0x60, 0x99,
	0x62, 0x2f, 0x02, 0x4a, 0x44, 0x12, 0xc6, 0xa0, 0x7a, 0xce, 0x9c, 0x0a, 0xf6, 0x32, 0x11, 0x77,
	0xfc, 0x0a, 0x4a, 0xd7, 0x69, 0x57, 0x75, 0x45, 0x4c, 0xe8, 0x9f, 0x9c, 0x24, 0x6b, 0x97, 0xe4,
	0x29, 0xad, 0x9f, 0x12, 0xa8, 0x63, 0x46, 0x03, 0xfc, 0x1c, 0xb4, 0xe0, 0xab, 0x13, 0x65, 0x95,
	0x6b, 0x39, 0x68, 0xc4, 0xbd, 0x24, 0x09, 0xe2, 0x26, 0x54, 0x18, 0x9d, 0x07, 0x34, 0x74, 0x58,
	0x1c, 0x26, 0x85, 0x35, 0xb2, 0xea, 0xe2, 0xf5, 0xa7, 0x71, 0xe8, 0x30, 0xd7, 0xf7, 0xfe, 0x50,
	0x3f, 0x4b, 0xc1, 0xfb, 0x50, 0x71, 0xf3, 0xa7, 0x45, 0x75, 0x55, 0x4c, 0xfd, 0xdf, 0x3b, 0x9e,
	0x4d, 0x56, 0xf3, 0x5a, 0x3f, 0x24, 0x28, 0xa6, 0x1b, 0xe1, 0x53, 0x88, 0xe3, 0x74, 0xaf, 0x1a,
	0x11, 0xf7, 0x3b, 0x27, 0xd3, 0x84, 0xca, 0x94, 0x46, 0x97, 0xa1, 0x1b, 0xe4, 0xcd, 0x95, 0xc9,
	0xaa, 0xeb, 0x81, 0xcd, 0xe0, 0x67, 0xa0, 0x45, 0x8c, 0x06, 0x51, 0x5d, 0x13, 0x80, 0xe5, 0x96,
	0xf9, 0x60, 0x49, 0x12, 0x6b, 0xdb, 0x50, 0x5b, 0xdf, 0x21, 0xae, 0xc3, 0x96, 0x35, 0x31, 0xcd,
	0x73, 0xc3, 0xea, 0x13, 0xfd, 0xc4, 0xd0, 0x2d, 0xfb, 0xdc, 0x3e, 0x1b, 0xe9, 0x68, 0x03, 0x97,
	0x41, 0xfb, 0xdc, 0xb3, 0x75, 0x82, 0x24, 0x5c, 0x02, 0x75, 0xd0, 0x33, 0x6d, 0x24, 0xf3, 0xdb,
	0xe9, 0x70, 0x34, 0x46, 0x0a, 0x0f, 0x9f, 0x19, 0xfa, 0xd8, 0x46, 0x6a, 0xfb, 0x3d, 0xa8, 0xfc,
	0x53, 0xc2, 0x55, 0x28, 0x0b, 0xae, 0x89, 0x65, 0xd8, 0x68, 0x03, 0x6b, 0x20, 0x99, 0x48, 0xe2,
	0x47, 0x1f, 0xc9, 0xb8, 0x00, 0xf2, 0xc7, 0x3e, 0x52, 0x70, 0x11, 0x94, 0x81, 0x61, 0x21, 0x95,
	0x5f, 0x4e, 0x7a, 0x67, 0x48, 0x6b, 0xcf, 0x40, 0x13, 0xeb, 0xe5, 0xe4, 0x46, 0x02, 0xad, 0x40,
	0x71, 0xd0, 0x1b, 0x9f, 0x1a, 0x56, 0x1f, 0x49, 0xdc, 0x38, 0x1a, 0x1a, 0x26, 0x37, 0x64, 0xbc,
	0x09, 0xa5, 0xf1, 0xa8, 0x47, 0xfa, 0xdc, 0x52, 0xb8, 0x75, 0x7c, 0x6a, 0x98, 0x22, 0xa6, 0x62,
	0x04, 0x9b, 0x1f, 0x74, 0x32, 0xd0, 0x2d, 0xbb, 0x67, 0x1b, 0x43, 0x0b, 0x69, 0x3c, 0x7e, 0x34,
	0xb4, 0x6d, 0x11, 0x2f, 0x74, 0xbf, 0xcb, 0x50, 0x4b, 0xf7, 0x35, 0xa6, 0xe1, 0x8d, 0x7b, 0x49,
	0xf1, 0x6b, 0x50, 0xfa, 0x94, 0xe1, 0xe5, 0x78, 0x97, 0x02, 0xd5, 0xd8, 0x5a, 0x77, 0xa6, 0xbf,
	0xe7, 0x01, 0x14, 0x12, 0xb9, 0xc0, 0xdb, 0x79, 0x7c, 0x4d, 0x7c, 0x1a, 0x3b, 0xbf, 0xf9, 0x53,
	0xe8, 0x5b, 0x28, 0x24, 0x3a, 0xb2, 0x02, 0x5d, 0x13, 0x96, 0xc6, 0x76, 0x27, 0xd1, 0xcf, 0x4e,
	0xa6, 0x9f, 0x1d, 0x9d, 0xeb, 0x27, 0x47, 0x26, 0x22, 0xb2, 0x82, 0x5c, 0x53, 0x95, 0x7b, 0x91,
	0xfb, 0xa0, 0x72, 0x75, 0xc1, 0xf7, 0xc4, 0x1b, 0xff, 0xe5, 0x7c, 0xab, 0x22, 0x74, 0x51, 0x10,
	0x69, 0x6f, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x99, 0xc0, 0x12, 0x3b, 0xf4, 0x05, 0x00, 0x00,
}
